import type { LocationDefinition, LocationId } from "./types";
import { MAX_WORLD_WIDTH } from "./regions";

export const WORLD_WIDTH = MAX_WORLD_WIDTH;
export const GAME_WIDTH = 960;
export const GAME_HEIGHT = 540;
export const STREET_Y = 418;

export const LOCATIONS: LocationDefinition[] = [
  {
    id: "park",
    name: "Mossy Pocket Park",
    x: 920,
    interactionRadius: 126,
    interactive: true,
    sign: "MOSSY POCKET PARK",
    kind: "decorative",
    description: "Evergreens, benches, crows, and one optimistically dry patch.",
    regionId: "neighborhood-west",
    rarity: 1,
    interactionIds: ["park-walk"],
    outdoor: true,
  },
  {
    id: "music-store",
    name: "Mossback Music",
    x: 1240,
    interactionRadius: 126,
    interactive: true,
    sign: "MOSSBACK MUSIC",
    kind: "shop",
    description: "Used instruments and new reasons to believe you could join a band.",
    regionId: "neighborhood-west",
    rarity: 2,
    interactionIds: ["music-browse", "guitar-buy"],
  },
  {
    id: "bar",
    name: "The Crooked Salmon",
    x: 1510,
    interactionRadius: 126,
    interactive: true,
    sign: "THE CROOKED SALMON",
    kind: "shop",
    description: "A neighborhood bar with excellent fries and advanced zoning discourse.",
    regionId: "neighborhood-west",
    rarity: 2,
    interactionIds: ["bar-evening"],
  },
  {
    id: "convenience",
    name: "The Bare Minimum",
    x: 1815,
    interactionRadius: 120,
    interactive: true,
    sign: "THE BARE MINIMUM",
    kind: "shop",
    description: "Hot food, cold lighting, and prices that only feel moderately personal.",
    regionId: "arrival",
    rarity: 1,
    interactionIds: ["cheap-meal"],
  },
  {
    id: "coffee",
    name: "Drizzle & Steam",
    x: 2150,
    interactionRadius: 126,
    interactive: true,
    sign: "DRIZZLE & STEAM",
    kind: "shop",
    description: "Coffee calibrated for weather, ethics, and social positioning.",
    regionId: "arrival",
    rarity: 1,
    interactionIds: ["coffee-order", "coffee-recover"],
    eventIds: ["coffee-opportunity"],
  },
  {
    id: "apartment",
    name: "Tiny Apartment",
    x: 2530,
    interactionRadius: 118,
    interactive: true,
    sign: "TINY APARTMENT",
    kind: "home",
    description: "One tiny apartment, centrally located between optimism and rent.",
    regionId: "arrival",
    rarity: 1,
    interactionIds: ["stay-home"],
    eventIds: ["sleep"],
  },
  {
    id: "job-board",
    name: "Neighborhood Job Board",
    x: 2810,
    interactionRadius: 112,
    interactive: true,
    sign: "JOBS, PROBABLY",
    kind: "board",
    description: "A corkboard connecting human potential with laminated vacancies.",
    regionId: "arrival",
    rarity: 1,
    interactionIds: [],
    eventIds: ["job-listing"],
  },
  {
    id: "workplace",
    name: "Cascadia Solutions",
    x: 3180,
    interactionRadius: 132,
    interactive: true,
    sign: "CASCADIA SOLUTIONS",
    kind: "work",
    description: "Strategic adjacency, calendar alignment, and one actual task.",
    regionId: "arrival",
    rarity: 1,
    interactionIds: [],
    eventIds: ["work-shift"],
  },
  {
    id: "transit",
    name: "Arrival Block Transit",
    x: 3500,
    interactionRadius: 122,
    interactive: true,
    sign: "TRANSIT, EVENTUALLY",
    kind: "decorative",
    description: "A transit entrance currently serving hope on a delayed schedule.",
    regionId: "arrival",
    rarity: 1,
    interactionIds: ["transit-trip"],
  },
  {
    id: "theater",
    name: "The Damp Curtain",
    x: 3900,
    interactionRadius: 132,
    interactive: true,
    sign: "THE DAMP CURTAIN",
    kind: "shop",
    description: "A local theater where every production has one chair with history.",
    regionId: "neighborhood-east",
    rarity: 2,
    interactionIds: ["theater-usher"],
  },
  {
    id: "laundromat",
    name: "Spin Cycle of Concern",
    x: 4145,
    interactionRadius: 100,
    interactive: false,
    sign: "LAUNDRY SOON",
    kind: "decorative",
    description: "A future source of clean clothes and recurring obligations.",
    regionId: "neighborhood-east",
    rarity: 1,
    interactionIds: [],
  },
  {
    id: "art-store",
    name: "Very Serious Art Supply",
    x: 4340,
    interactionRadius: 126,
    interactive: true,
    sign: "VERY SERIOUS ART",
    kind: "shop",
    description: "Archival paper, intimidating pencils, and an employee who can sense hesitation.",
    regionId: "neighborhood-east",
    rarity: 2,
    interactionIds: ["sketchbook-buy"],
  },
];

export const LOCATION_BY_ID = Object.fromEntries(
  LOCATIONS.map((location) => [location.id, location]),
) as Record<LocationId, LocationDefinition>;
